name: debris_cover_smb_env
channels:
  - conda-forge
  - defaults
dependencies:
 # core data science 
 - python
 - scipy
 - scikit-image
 - numpy
 - pandas
 - matplotlib
 - astropy
 - beautifulsoup4
 - bokeh
 - bzip2 
 - cairo 
 - cartopy
 - jupyterlab 
 - ipympl
 - bookeh
 - wget 
 - requests
 
 # geospatial (raster+vector)
 - gdal
 - rasterio
 - geopandas
 - pygeos
 - shapely
 - contextily
 - descartes
 - affine
 - earthaccess
 - xdem
 - arosics
 
 # misc
 - pip
 - psutil
  - pip:
   - geojson
   - matplotlib-colorbar
   - matplotlib-scalebar
   - multiprocess
   - p-tqdm
   - ppft
   - srtm4
   - urllib3
   - xmltodict
   # rotation_matrices
   - pyquaternion
   # misc
   - p_tqdm
   # geospatial+plotting
   - "--editable=git+https://github.com/dshean/pygeotools.git#egg=pygeotools"
   - "--editable=git+https://github.com/dshean/demcoreg.git#egg=demcoreg"
   - "--editable=git+https://github.com/ShashankBice/imview.git@jglac_version#egg=imview" 
